version: '3'
services:
  tekxit:
    build:
      context: .
      args:
        VERSION: 1.0.7.1
    environment:
      - JAVA_XMS=2G
      - JAVA_XMX=7G
    ports:
      - 25565:25565
    volumes:
      - ./data:/data
